emoji_server_ids = [] # emoji will be looked up by name from these servers only
train_types = [
	# possible options for matching, not provided = matches all
	# { type = "IC", line = "1",  line_startswith = "1", network = "SBB"}
	# possible options for display
	# { emoji = "ica,ic1", color = "#ff0404", hide_line_number = true, always_show_train_number = true }
	# ===== DB HAFAS provided train types =====
	{ type = "A", emoji = "A_", color = "#f49100" },
	{ type = "AST", emoji = "ast", color = "#ffd700" },
	{ type = "Bus", emoji = "Bus", color = "#a3167e" },
	{ type = "Bus", line_startswith = "N", emoji = "BusN", color = "#a3167e" },
	{ type = "Bus", line_startswith = "X", emoji = "BusX", color = "#a3167e" },
	{ type = "CB", emoji = "cb", color = "#c91432" },
	{ type = "Bus", emoji = "Bus", color = "#a3167e" },
	{ type = "CJX", emoji = "Ja|Jb", color = "#ff4f00" },
	{ type = "D", emoji = "da|db", color = "#ff0404", always_show_train_number = true },
	{ type = "EC", emoji = "eca|ecb", color = "#ff0404", always_show_train_number = true },
	{ type = "ECE", emoji = "eca|ece", color = "#ff0404", always_show_train_number = true },
	{ type = "EIC", emoji = "ia|ib", color = "#ff0404", always_show_train_number = true },
	{ type = "EN", emoji = "na|nb", color = "#282559", always_show_train_number = true },
	{ type = "EST", emoji = "Ta|Tb", color = "#ff0404", always_show_train_number = true },
	{ type = "EV", emoji = "Sa|Sb" },
	{ type = "Fähre", emoji = "Faehre", color = "#00a4db" },
	{ type = "FEX", emoji = "fex0|fex1", color = "#ff4f00" },
	{ type = "FLX", emoji = "La|Lb", color = "#72d800", always_show_train_number = true },
	{ type = "IC", emoji = "ca|cb", color = "#ff0404", always_show_train_number = true },
	{ type = "ICD", emoji = "ca|icd1", color = "#ff0404" },
	{ type = "ICE", emoji = "ca|Cb", color = "#ff0404", always_show_train_number = true },
	{ type = "ICN", emoji = "icn0|icn1", color = "#282559", always_show_train_number = true },
	{ type = "IR", emoji = "Ia|db", color = "#ff0404", always_show_train_number = true },
	{ type = "IRE", emoji = "ia|ib", color = "#ff4f00" },
	{ type = "KM", emoji = "ka|kb", color = "#204a87" },
	{ type = "KML", emoji = "La|Lb", color = "#204a87" }, # FIXME
	{ type = "KS", emoji = "sa|sb", color = "#204a87" },
	{ type = "L", emoji = "l0|Rb", color = "#204a87" },
	{ type = "M", emoji = "metro", color = "#014e8d" },
	{ type = "MEX", emoji = "m0|m1", color = "#204a87" },
	{ type = "NJ", emoji = "Na|Nb", color = "#282559", always_show_train_number = true },
	{ type = "O-Bus", emoji = "Bus", color = "#a3167e" },
	{ type = "R", emoji = "Ra|Rb", color = "#204a87" },
	{ type = "RB", emoji = "Ba|Bb", color = "#204a87" },
	{ type = "RE", operator = "Nederlandse Spoorwegen", emoji = "ns0|ns1", color = "#204a87" },
	{ type = "RE", emoji = "Ea|Eb", color = "#ff4f00" },
	{ type = "RER", emoji = "RER", color = "#2c8e4e" },
	{ type = "REX", emoji = "Ea|EXb", color = "#ff4f00" },
	{ type = "RJ", emoji = "2a|2b", color = "#c63131", always_show_train_number = true },
	{ type = "RJX", emoji = "1a|1b", color = "#c63131", always_show_train_number = true },
	{ type = "RNV", emoji = "Tram", color = "#c5161c" },
	{ type = "RS", emoji = "RS", color = "#2c8e4e" },
	{ type = "RUF", emoji = "ruf", color = "#ffd700" },
	 # network = "AT": matches if station IDs start with 81…
	{ type = "S", network = "AT", emoji = "ATS", color = "#0096d8" },
	# network = "AVG": matches if operator is "Albtal-Verkehrs-Gesellschaft mbH"
	{ type = "S", network = "AVG", emoji = "KAS", color = "#c5161c" },
	{ type = "S", line_startswith = "L", emoji = "SL", remove_line_startswith = true, color = "#c5161c" },
	{ type = "S", line_startswith = "N", emoji = "SN", color = "#c5161c" },
	{ type = "S", emoji = "SBahn", color = "#2c8e4e" },
	{ type = "SB", emoji = "SB", color = "#014e8d" },
	{ type = "Schw-B", emoji = "SchwB", color = "#014e8d" },
	{ type = "SEV", emoji = "Sa|Sb" },
	{ type = "SKW", emoji = "SBahn", color = "#2c8e4e" },
	# network = "Ü": matches if operator is "üstra Hannoversche Verkehrsbetriebe AG"
	{ type = "STB", network = "Ü", emoji = "UE", color = "#78b41d" },
	{ type = "STB", emoji = "STB", color = "#c5161c" },
	# network = "KVB": matches if inside geofence around Köln/Bonn
	# lines 61,62,65 are normal tram lines
	{ type = "STR", network = "KVB", line = "61", emoji = "STR", color = "#c5161c" },
	{ type = "STR", network = "KVB", line = "62", emoji = "STR", color = "#c5161c" },
	{ type = "STR", network = "KVB", line = "65", emoji = "STR", color = "#c5161c" },
	{ type = "STR", network = "KVB", emoji = "STB", color = "#c5161c" },
	{ type = "STR", emoji = "STR", color = "#c5161c" },
	{ type = "SVG", emoji = "fex0|fex1", color = "#ff4f00" },
	{ type = "TER", emoji = "ta|tb", color = "#204a87" },
	{ type = "TGV", emoji = "Ta|Tb", color = "#ff0404", always_show_train_number = true },
	{ type = "TLK", emoji = "ta|tb", color = "#ff0404", always_show_train_number = true }, # FIXME
	{ type = "Tram", emoji = "Tram", color = "#c5161c" },
	# network = "BVG": matches if inside geofence around Berlin
	{ type = "U", line = "1", network = "BVG", emoji = "U1b", color = "#7dad4c", hide_line_number = true },
	{ type = "U", line = "2", network = "BVG", emoji = "U2b", color = "#da421e", hide_line_number = true },
	{ type = "U", line = "3", network = "BVG", emoji = "U3b", color = "#16683d", hide_line_number = true },
	{ type = "U", line = "4", network = "BVG", emoji = "U4b", color = "#f0d722", hide_line_number = true },
	{ type = "U", line = "5", network = "BVG", emoji = "U5b", color = "#7e5330", hide_line_number = true },
	{ type = "U", line = "6", network = "BVG", emoji = "U6b", color = "#8c6dab", hide_line_number = true },
	{ type = "U", line = "7", network = "BVG", emoji = "U7b", color = "#528dba", hide_line_number = true },
	{ type = "U", line = "8", network = "BVG", emoji = "U8b", color = "#224f86", hide_line_number = true },
	{ type = "U", line = "9", network = "BVG", emoji = "U9b", color = "#f3791d", hide_line_number = true },
	{ type = "U", line = "12", network = "BVG", emoji = "U12b", color = "#7dad4c", hide_line_number = true },
	# network = "HHA": matches if inside geofence around Hamburg
	{ type = "U", line = "1", network = "HHA", emoji = "UHH1", color = "#0073c0", hide_line_number = true },
	{ type = "U", line = "2", network = "HHA", emoji = "UHH2", color = "#ff2e17", hide_line_number = true },
	{ type = "U", line = "3", network = "HHA", emoji = "UHH3", color = "#ffd939", hide_line_number = true },
	{ type = "U", line = "4", network = "HHA", emoji = "UHH4", color = "#00b2b1", hide_line_number = true },
	# network = "MVG": matches if inside geofence around München
	{ type = "U", line = "1", network = "MVG", emoji = "U1m", color = "#447335", hide_line_number = true },
	{ type = "U", line = "2", network = "MVG", emoji = "U2m", color = "#bb0534", hide_line_number = true },
	{ type = "U", line = "3", network = "MVG", emoji = "U3m", color = "#e4692a", hide_line_number = true },
	{ type = "U", line = "4", network = "MVG", emoji = "U4m", color = "#35aa83", hide_line_number = true },
	{ type = "U", line = "5", network = "MVG", emoji = "U5m", color = "#b87c0a", hide_line_number = true },
	{ type = "U", line = "6", network = "MVG", emoji = "U6m", color = "#2362ae", hide_line_number = true },
	{ type = "U", line = "7", network = "MVG", emoji = "U7m", color = "#447335", hide_line_number = true },
	{ type = "U", line = "8", network = "MVG", emoji = "U8m", color = "#e4692a", hide_line_number = true },
	# network = "NRW": matches if inside geofence around NRW
	{ type = "U", network = "NRW", emoji = "STB", color = "#c5161c" },
	# network = "VAG": matches if inside geofence around Nürnberg
	{ type = "U", line = "1", network = "VAG", emoji = "U1n", color = "#176fc1", hide_line_number = true },
	{ type = "U", line = "2", network = "VAG", emoji = "U2n", color = "#ed1c24", hide_line_number = true },
	{ type = "U", line = "3", network = "VAG", emoji = "U3n", color = "#4cc3bc", hide_line_number = true },
	# network = "VGF": matches if inside geofence around Frankfurt (Main)
	{ type = "U", line = "1", network = "VGF", emoji = "U1f", color = "#c52b1e", hide_line_number = true },
	{ type = "U", line = "2", network = "VGF", emoji = "U2f", color = "#00ab4f", hide_line_number = true },
	{ type = "U", line = "3", network = "VGF", emoji = "U3f", color = "#345aaf", hide_line_number = true },
	{ type = "U", line = "4", network = "VGF", emoji = "U4f", color = "#fc5cac", hide_line_number = true },
	{ type = "U", line = "5", network = "VGF", emoji = "U5f", color = "#0c7d3e", hide_line_number = true },
	{ type = "U", line = "6", network = "VGF", emoji = "U6f", color = "#0082ca", hide_line_number = true },
	{ type = "U", line = "7", network = "VGF", emoji = "U7f", color = "#f19e2d", hide_line_number = true },
	{ type = "U", line = "8", network = "VGF", emoji = "U8f", color = "#ca7fbe", hide_line_number = true },
	{ type = "U", line = "9", network = "VGF", emoji = "U9f", color = "#ffd939", hide_line_number = true },
	# network = "WL": matches if operator = "Wiener Linien"
	{ type = "U", line = "1", network = "WL", emoji = "U1", color = "#ed1d26", hide_line_number = true },
	{ type = "U", line = "2", network = "WL", emoji = "U2", color = "#9e50af", hide_line_number = true },
	{ type = "U", line = "3", network = "WL", emoji = "U3", color = "#f47114", hide_line_number = true },
	{ type = "U", line = "4", network = "WL", emoji = "U4", color = "#1ea366", hide_line_number = true },
	{ type = "U", line = "5", network = "WL", emoji = "U5", color = "#0098a1", hide_line_number = true },
	{ type = "U", line = "6", network = "WL", emoji = "U6", color = "#926131", hide_line_number = true },
	{ type = "U", line_startswith = "m", emoji = "M", remove_line_startswith = true, color = "#c5161c" },
	{ type = "U", emoji = "U_", color = "#014e8d" },
	{ type = "WB", emoji = "wa|wb", color = "#2e86ce" },
	{ type = "west", emoji = "wa|wb", color = "#2e86ce" },
	{ type = "WLB", emoji = "wlb", color = "#175a97" },
	{ type = "ZahrR", emoji = "zahnr" },
	# network = "ST": matches if operator any of "Blauwnet", "Arriva Nederland", "RRReis", "R-net"
	{ type = "", network = "ST", emoji = "s0|s1", color = "#204a87" },
	# ===== manual checkin train types =====
	{ type = "bike", emoji = "sbbvelo" },
	{ type = "boat", emoji = "sbbboot" },
	{ type = "car", emoji = "sbbauto" },
	{ type = "coach", emoji = "sbbcoach" },
	{ type = "plane", emoji = "sbbflug" },
	{ type = "steam", emoji = "sbbsteam" },
	{ type = "walk", emoji = "sbbwalk" },
	# ===== fallback for unknown train types =====
	{ emoji = "generic" }
]
